### ISSUE TITLE
Creating a New Fundraise

### ISSUE THREAD

**Issue by SharayahDesigns** [JoeJorgensen/WeCare#10]
Problem 1. 
On the New Campaign page, if you add a new campaign it does not let you know it worked.

Problem 2. 
Sometimes the new campaign will not submit at all if you don't hit the submit button twice before refreshing. 

Problem 3. 
The new campaign will not submit at all if you add cents greater than 3 numbers. 
example ($200.987)  It will not show an error or that the page has a problem. 

problem 4. 
I have tried to just add a normal fundraising event for the the category "Events" and it refuses to take my request.

**Comment by Randycl808** [comment]
This is helpful, thank you.
