### ISSUE TITLE
Name of person dontating

### ISSUE THREAD

**Issue by katbrenda** [JoeJorgensen/WeCare#15]
No place to add my name when I make a donation. is it supposed to auto populate my name with my donation, or was I supposed to be able to type it in somewhere?

**Comment by JoeJorgensen** [comment]
Yep, that's all thanks to your Authenticated Token, we already have the users information so we can then render the donations with the users name and image making it an easier experience for the user.

**Comment by katbrenda** [comment]
My name did not populate when I made a donation. Thats what made me to wonder what was supposed to happen.
