### ISSUE TITLE
Anonymous Doesn't Work

### ISSUE THREAD

**Issue by jessicasnguyen** [JoeJorgensen/WeCare#17]
### Issue
When selecting the anonymous checkbox it still shows user information.

### Steps to Recreate
1. Navigate to the Campaign page ( This was done on the barn fire page)
2. Click Donate Button
3. Fill out Information on either Pay With Wallet or Pay WIth Card (I've attempted with both with the same result)
4. Click the Anonymous checkbox
5. Click Submit
6. When page is refreshed, it shows the Name attached to the donation instead of marking it as Anonymous.

### Screenshots
Four of the "Tester" donations were submitted with the Anonymous checkbox checked.
<img width="982" alt="Screen Shot 2022-04-22 at 3 09 46 PM" src="https://user-images.githubusercontent.com/72749009/164793958-be578734-9a6f-41a0-b6a1-a90098d5b618.png">

**Comment by Randycl808** [comment]
Thank you this was helpful feedback.
