### ISSUE TITLE
Current Balance For Campaign Not Correct

### ISSUE THREAD

**Issue by jessicasnguyen** [JoeJorgensen/WeCare#21]
### Issue
The current balance of the campaign doesn't show the correct amount

### Steps to recreate
1. Navigate to the Campaign page ( This was done on the barn fire page)
2. Donations are being excluded
3. If I refresh the page, only the current donations I've added show up
4. If I navigate away from the page and back it seems to "reset" the count
5. In the screenshot only the last two donations are showing

### Screenshots
<img width="854" alt="Screen Shot 2022-04-22 at 3 16 14 PM" src="https://user-images.githubusercontent.com/72749009/164795013-f98d4a77-be45-4988-aa47-39add139d576.png">
<img width="964" alt="Screen Shot 2022-04-22 at 3 16 26 PM" src="https://user-images.githubusercontent.com/72749009/164795072-5cb07f3a-4b20-4f05-a738-50fb1456efff.png">

**Comment by JoeJorgensen** [comment]
That's weird I haven't come across that one yet but that's definitely an issue and our payment system is pretty new so  we have a lot to adjust, this was super helpful though thank you! I'm having trouble trying to replicate this would you mind being a little more specific on how you got it to do this.

**Comment by jessicasnguyen** [comment]
Sure! I did some more testing and it seems to be tied to the other bug I submitted where someone could go through the donation without adding anything.

### Steps to Replicate
1. Logged in
2. Navigated to Campaign (in this case the barn)
3. Click the donate button
4. If I put in an amount and submitted it populated as expected
6. If I didn't include and amount and instead just hit submit, it zeroed the total out

### Screenshots
Before adding a new donation
<img width="1037" alt="Screen Shot 2022-04-22 at 6 38 21 PM" src="https://user-images.githubusercontent.com/72749009/164841875-fa216ab7-0f92-4633-8ff4-6f14cc6390f0.png">

After adding $50 into the donation amount field
<img width="1038" alt="Screen Shot 2022-04-22 at 6 39 28 PM" src="https://user-images.githubusercontent.com/72749009/164840775-b380e404-9b49-49ff-a8a7-7559383cf689.png">

After submitting without putting an amount in the donation field
<img width="1036" alt="Screen Shot 2022-04-22 at 6 39 56 PM" src="https://user-images.githubusercontent.com/72749009/164840898-42ca5b40-b1fa-435e-8678-440768ca21ac.png">

**Comment by jessicasnguyen** [comment]
### Forgot screenshot to show all donations
<img width="1027" alt="Screen Shot 2022-04-22 at 6 40 12 PM" src="https://user-images.githubusercontent.com/72749009/164842380-28a3e2a1-3180-4dde-aeb3-472dfc1c13c1.png">

**Comment by JoeJorgensen** [comment]
Okay sweet I thought so, I fixed that bug it’s tied to and the whole campaign page in general, so it should be all good to go I’m glad you spotted this, thanks!
