### ISSUE TITLE
My Donations Page Cards

### ISSUE THREAD

**Issue by jessicasnguyen** [JoeJorgensen/WeCare#23]
### Expected
Would expect the cards for the campaigns to be clickable, or for the name of the campaign on the card to be clickable to take you to the campaign, but there wasn't any clickable links on the cards.

**Comment by JoeJorgensen** [comment]
Yes I definitely agree, we haven't really incorporated that yet just because we haven't started styling yet so we're going to lock down on UX as were styling.
